# Generated by Django 3.2.16 on 2023-03-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='discpunt_percent',
            new_name='discount_percent',
        ),
    ]
